disabled_rules:
  - line_length
  - identifier_name
  - trailing_whitespace
  - function_body_length
  - type_name
  - cyclomatic_complexity
  - force_cast
  - type_body_length
  - file_length
  - empty_parentheses_with_trailing_closure
excluded:
  - Carthage
  - Pods
